[package]
name = "nvimTimeMachine"
version = "0.1.0"
edition = "2021"

[dependencies]
clap       = { version = "4.5.38", features = ["derive"] }
walkdir    = "2.3"
zip        = "2.6.1"
indicatif  = "0.17"
dirs       = "6.0.0"
chrono     = { version = "0.4.41" }
dialoguer = "0.11.0"
